### ISSUE TITLE
Add Static Position Methods

### ISSUE THREAD

**Issue by Vanessamae23** [cs3217-2324/group-project-tower-forge#34]
Currently the position of the HUDs are kept inside the specific entities, I think porting over to a GameConstant with Position, Layer struct is better

**Comment by sp4ce-cowboy** [comment]
Should we separate them from Entity entirely? Since the UI components don't really need a UUID, maybe we could create a UIElement protocol and have CoinElement, HeartElement, TowerSelectionElement etc. This way we could entirely decouple View-only information (i.e. HUD) from Model information (i.e. TFEntity).

**Comment by Vanessamae23** [comment]
I think the rationale I put HUD inside entity is to be able to access the HomeComponent which contains the data part of the game hence making it easier to listen to changes. I have not thought about a way to not do this and have a separate component yet still listen to changes dynamically
